[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
frontend.workspace = true
axum = "0.6"
dioxus = { workspace = true }
dioxus-ssr = { version = "0.3" }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3", features = ["fs"] }
